language: php
php:
  - "7.2"
before_script:
  - composer selfupdate

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpcs src

notifications:
  email:
    on_success: never
    on_failure: change
